name: Release

on:
  push:
    tags:
      - v*

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: "Build project"
        run: uv run build

      - name: "Publish to PyPI"
        run: uv publish --username __token__ --password ${{ secrets.PYPI_TOKEN }}
